[tools]
"aqua:cli/cli" = "2.83.1"
"aqua:go-task/task" = "3.45.5"
"aqua:GoogleContainerTools/container-structure-test" = "1.22.0"
"aqua:jqlang/jq" = "1.8.1"
"aqua:mikefarah/yq" = "4.49.1"
"go" = "1.25"

[hooks]
postinstall = [
  "mkdir -p {{config_root}}/.cache",
]
